// ✅ ALREADY DONE — do not edit this file.
// Requests to /sessions are sent to the backend automatically,
// so in your code you can just write fetch('/sessions').

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  plugins: [react(), tailwindcss()],
  server: {
    port: 5173,
    proxy: {
      '/sessions': 'http://localhost:3001',
    },
  },
});
