// ✅ ALREADY DONE — do not edit this file.
// The server is set up and running. Write your code in routes/sessions.js.

const express = require('express');
const cors = require('cors');
const sessionsRouter = require('./routes/sessions');

const app = express();

app.use(cors());
app.use(express.json());

app.use('/sessions', sessionsRouter);

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`Gaming café server running on http://localhost:${PORT}`);
});
