// ✅ ALREADY DONE — do not edit this file.
// This is the finished session card UI. Just use it from App.jsx like this:
//
//   <SessionCard
//     session={session}                  // one session object from the server
//     onStop={(id) => ...}               // runs when "Stop Playing" is clicked
//     onAddTime={(id, minutes) => ...}   // runs when "Add Time" is clicked
//   />

import { useState } from 'react';

const BADGE_STYLES = {
  Bronze: 'bg-orange-100 text-orange-800 border-orange-400',
  Silver: 'bg-slate-200 text-slate-700 border-slate-400',
  Gold: 'bg-yellow-100 text-yellow-800 border-yellow-400',
};

const BADGE_ICONS = { Bronze: '🥉', Silver: '🥈', Gold: '🥇' };

function Badge({ name }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-0.5 text-xs font-semibold ${BADGE_STYLES[name]}`}
    >
      {BADGE_ICONS[name]} {name}
    </span>
  );
}

export default function SessionCard({ session, onStop, onAddTime }) {
  const [minutes, setMinutes] = useState('');
  const isActive = session.status === 'active';
  const hasGold = session.badges.includes('Gold');

  const handleAddTime = () => {
    const value = parseInt(minutes, 10);
    if (!value || value <= 0) return;
    onAddTime(session.id, value);
    setMinutes('');
  };

  return (
    <div
      className={`rounded-xl border p-4 shadow-sm transition ${
        isActive
          ? 'border-emerald-300 bg-white'
          : 'border-gray-200 bg-gray-100 opacity-80'
      }`}
    >
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="text-lg font-semibold text-gray-900">
            {session.playerName}
          </h3>
          <p className="text-sm text-gray-600">
            {isActive ? (
              <>
                <span className="mr-1.5 inline-block h-2 w-2 animate-pulse rounded-full bg-emerald-500" />
                {session.elapsedMinutes} game min
              </>
            ) : (
              <>Final time: {session.elapsedMinutes} game min</>
            )}
          </p>
        </div>
        <span
          className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${
            isActive
              ? 'bg-emerald-100 text-emerald-700'
              : 'bg-gray-200 text-gray-600'
          }`}
        >
          {isActive ? 'Active' : 'Completed'}
        </span>
      </div>

      {/* Badge row: unlocked badges, MAX indicator at Gold, grey chip for
          completed sessions that never reached Bronze */}
      <div className="mt-3 flex flex-wrap items-center gap-2">
        {session.badges.map((badge) => (
          <Badge key={badge} name={badge} />
        ))}
        {hasGold && (
          <span className="inline-flex items-center rounded-full bg-purple-600 px-2.5 py-0.5 text-xs font-bold uppercase tracking-wider text-white">
            MAX
          </span>
        )}
        {!isActive && session.badges.length === 0 && (
          <span className="inline-flex items-center rounded-full border border-gray-300 bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-500">
            No badge
          </span>
        )}
      </div>

      {isActive && (
        <div className="mt-4 flex flex-wrap items-center gap-2">
          <button
            onClick={() => onStop(session.id)}
            className="rounded-lg bg-red-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-red-700"
          >
            Stop Playing
          </button>
          <div className="flex items-center gap-1.5">
            <input
              type="number"
              min="1"
              value={minutes}
              onChange={(e) => setMinutes(e.target.value)}
              placeholder="min"
              className="w-20 rounded-lg border border-gray-300 px-2 py-1.5 text-sm focus:border-indigo-500 focus:outline-none"
            />
            <button
              onClick={handleAddTime}
              className="rounded-lg bg-indigo-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-indigo-700"
            >
              Add Time
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
